# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   There is no gem for Windows.  Install mysql.so from RubyForApache.
#   http://rubyforge.org/projects/rubyforapache
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
defaults: &defaults
  adapter: mysql
  username: xmas
  password: 
  socket: <%= ["/tmp/mysqld.sock",
               "/tmp/mysql.sock",
               "/var/mysql/mysql.sock",
               "/var/run/mysqld/mysqld.sock",
               "/opt/local/var/run/mysqld/mysqld.sock",
               "/opt/local/var/run/mysql5/mysqld.sock",
               "/var/lib/mysql/mysql.sock"].detect{|socket|
               File.exist?(socket)
               } %>    

development:
  database: xmas_adultz_development
  <<: *defaults                                                                 

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  database: xmas_adultz_test
  <<: *defaults                                                                 

production:
  database: xmas_adultz_production
  <<: *defaults                                                                 
